dist: trusty
language: scala

sudo: false

script: ./sbt compile scripted

matrix:
  include:
  # sbt-1.0 based on Scala 2.12 doesn't support JDK7
  - sudo: false
    jdk: oraclejdk8
  - sudo: required
    group: edge
    jdk: oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer
